version: '3'

services:
  jenkins:
    image: 'patkruk/jenkins'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      # - /app/node_modules # tells Docker not to map node_modules inside the container
      - .:/var/jenkins_home